/** Initial Endless mode values kept together for gameplay tuning. */
export const ENDLESS_SETTINGS = {
  width: 25,
  sectionRows: 24,
  residentSections: 5,
  logoChance: 0.5,
  minimumLogoSpacingRows: 24,
  extraStraightRowChance: 0.25,
  straightRunChance: 0.7,
  straightRunMinTiles: 12,
  straightRunMaxTiles: 18,
  maxVerticalStraightTiles: 4,
  maxHorizontalWallTiles: 10,
  powerCoresPerTile: 1 / 180,
  initialPowerCores: { min: 15, max: 17 },
  sectionPowerCores: { min: 3, max: 4 },
  firstEncounterMs: 5000,
  encounterIntervalMinMs: 5000,
  encounterIntervalMaxMs: 9000,
  waveMinEnemies: 1,
  waveMaxEnemies: 3,
  staggeredEntryMs: 400,
  deferredSpawnRetryMs: 500,
  spawnMarginTiles: 3,
  spawnSearchDepthTiles: 8,
  spawnMinCorridorSteps: 8,
  retireMarginTiles: 24,
  bugExitMarginTiles: 3,
} as const;
